# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b6120d09a7341121f0d382c28e6a7406e1a1b4936086afc347df32987f63580204290d07f56d9e30d1bc23c863c1626d402816442fce6ccc231078345309bb

test:
  secret_key_base: 2edd175280109b4f15198d983c37b176988c742e9d69f47c4af175d5ea1ef1d41477c1aa7acf79987655c1c7cfce5e86b3e7619b2b1a8022fffe208e5bc016ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
